[package]
name = "duplicate_zeros"
version = "0.1.0"
authors = ["Miroslav Kovar <miroslavkovar@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
